sudo: required

services:
  - docker

script:
  - docker build -t romansavrulin/ffmpeg-cuda:latest .

after_success:
  - set -e
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      docker push romansavrulin/ffmpeg-cuda:latest
    fi

