version: '3'
services:

  ffmpeg_nvidia:
    image: local/ffmpeg-nvidia:testing
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    container_name: "ffmpeg_nvidia"
    restart: unless-stopped
    stdin_open: true                        # interactive (-i)
    tty: true                               # tty (-t)
    volumes:
      - /path/to/scripts:/scripts
      - /path/to/videos:/videos

